* LOEL - Science, Technology, Engineering, Pattern Play

** NOTICE OF GitHub FAILURE
  - As of 2026-10-01 GitHub is failing to correctly display this document!
  - See the section below titled: ** Availability Of This Document


This repository is part of the [[https://github.com/GregDavidson/loel#readme][League of Extraordinary Learners]].

This repository will hold LOEL curricula materials for the Cognitive Sciences
according to the LOEL process for [[https://github.com/GregDavidson/loel/blob/main/Devel/creating-curricula.org][Creating and Developing LOEL Curricula]].

We are currently assembling resources on
- Science
- Technology
- Engineering
- Pattern Play <--> Mathematics

Would you like to participate?
** Availability Of This Document

This document is normally available at all the following urls:
- Codeberg :: 
- GitLab :: 
- GitHub ::
  - GitHub is currently failing to correctly process OrgMode documents.
  - as of 2026-10-01

Please consult the LICENCE or LICENSE.org or LICENSE.md file at the
top of this repository for freedoms and restrictions in your use of
the contents of this repository, including this document.

Even when not required, we would appreciate
- attribution with a reference to our respository,
- your sending us any improvements you make to these materials,
- information about any significant usage of these materials in your projects,
- and thank you!
